### ISSUE TITLE
Lua Bot Unable to dig any blocks on Multiplayer server

### ISSUE THREAD

**Issue by Davisa94** [Droog71/FCE_Lua_Robots#1]
Running the Dig() function with any of the following argument configurations does nothing. Dig(0,1,0) (expected to dig up) Result, nothing happened. Dig(0,-1,0) (expected to dig down) Result, nothing happened the block remained in place. Movement works as intended.

**Comment by Droog71** [comment]
> Running the Dig() function with any of the following argument configurations does nothing. Dig(0,1,0) (expected to dig up) Result, nothing happened. Dig(0,-1,0) (expected to dig down) Result, nothing happened the block remained in place. Movement works as intended.

I was only able to reproduce this bug using the "host game" button from the in-game pause menu.
When using a dedicated server, this bug does not occur.
There is an offset to the dig function in multiplayer games designed around dedicated servers.
```
if (NetworkManager.instance.mServerThread != null)
{
    cX = cX - 64;
    cY = cY - 64;
    cZ = cZ - 64;
}
```
Maybe after clicking the "host game" button this offset is applied, but the result is not the same as it would be on a dedicated server, causing a block to be removed far away from the robot.
